travis:
  secure:
    BINSTAR_TOKEN: djHOcKj3UthvLB2rQT1Tk5vGwAShG6v0ASBV/aI7r2O9lXJ1SBszZg0f0e+pB4DOOLUPvWZE9Ik/9URwfdCjYo9VJgOY7L2DqvdbJ1xUh0wHfJ5imYZJnvZzRxMe+4vd8ee8mPzv2W26nYYpnbaUacAoD05EZsYkVfFyz6qY9awCkxq0J7LlENRmras3DG9Vt/W0mtXA+5s0XrSbiEeJIzNATEMC+GOB2RCUGecS8ESHZQAIsVRJCKLqTOFyp+jMui3ca7G3BSMJklO3So5a1iKWR7R8G0guOu5ewmBLlxZcinhI3n3zCB7++ZqKCjo4GNN1XaZ/+xs/bOBJypPSAP6ScA/8lK2DVwhbOaP7JAnY5PdDV9QpLT4VaZHBY7wBcchvzWrR66TDxz0uWmWpZSkXs3jDdMNQUb2+6M/DJT787fT8y0MBqHP32t4D6ztnfwGH2HvMwUFaqGr7Xu70j5DSAs8vRut/qRcG1DZTckkN6IR7EiNUamUr5yz2dFpaCOQCxYNA8gwlWYy6pHWdEpncpbvr2rQ1ZmaGepo1N6b1LFIlS4tnHaR7o/N+RG/4TzGMKsFJ+ya4bu96DNDgcHdtOXvSBcdZRIfShob7UGf0bnCL31lTs4VauWQ2dDfuxe1mQNXMrgCHTR98PfuiUmcmAQkvZYFrVZc5hfWN/xg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
