travis:
  secure:
    BINSTAR_TOKEN: nCl+bWgu3lDL9UVp5iLxOlWTSu1qUdh8b6b3zyB0ZsCmEr2nDK/+pFHf47m0MmrbhlWlsQLdr0FvkWXm/n8+4uewYsJ61e1wBXqPR9aCFM+6lOux9jgRhtukNE6xdGeOui1XILG5ZQ0SF99D4K5RPgepZn8/T3OAmF0nbSS9RmUMlHppvqVLaIeaZ/U/c5N3XvUf7il/21kQldxLx3ZBs6RO4SSyIa1YXaJgbLbkDryD56BJtlkx+PhH5TddXHa73U7ZcB7A8y8OjzLaFCpcXU3QI0mmVpK8CFUOoNss4kIRCxHXT0EdqMs+989HlFzV5IsrAtP3F5GicAmvrE6E7K7/CrfKdpa5CctdsNS1lNcy7q0Wd7tocZF9GQcs8D/x4G761SHPf9gNYSRqpsB03rCwiTfpTFlIV1eqYSSk926XC/J6wKfGacc5PreEXxOvMBGbDKLMKWQmHa/cfq1YA39tdntGMohfK4S9Lw3KJ8oRqRx1QheFP95P+rou4HvwWAKiNoCI79+MvGxgNuydXxuFwz7uPPkLMlpz93kMdbLh28+GYM3DxAQQTo/wz3GytpdoM/c8dC65+jvyxCl38MqAJ/64T9LcObsknRIng+6eNSLDSWOroil92ocwsrUuTmHizR/Av7mkD9Yl0IfWHxVBsOXj/w8yg3dKmsH7+tM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
